### ISSUE TITLE
Criar Lambda Para Gerar o Token

### ISSUE THREAD

**Issue by jcmdsbr** [fiap-8soat-tc-one/tc-backend#45]
Receber o usuário/senha (fluxo privado) ou CPF (publico), através da URL de origem (api/v1/private, api/v1/public) validar o usuário PostgreSQL e gerar um token JWT.
 Adicionar o customer id no claims

**Comment by jcmdsbr** [comment]
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html

**Comment by cisikawa** [comment]
O Lambda deve realizar a seguinte chamada para o backend realizar a geracao do access token.

curl --location 'http://localhost:8080/api/public/v1/oauth/token' \
--header 'accept: application/json' \
--header 'Content-Type: application/json' \
--data '{ "document": 88404071039}'
Retorna:

{
"access_token": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI4ODQwNDA3MTAzOSIsImlkIjoiM2ZhODVmNjQtNTcxNy00NTYyLWIzZmMtMmM5NjNmNjZhZmE2IiwibmFtZSI6Ik15bGxlciBTYWthZ3VjaGkiLCJlbWFpbCI6Im15bGxlcnNha2FndWNoaUBnbWFpbC5jb20iLCJkb2N1bWVudCI6Ijg4NDA0MDcxMDM5IiwiaWF0IjoxNzMwODMyMjExLCJleHAiOjE3MzA4MzU4MTF9.-3fSGtEZkm9BzJBv4BRHvPzkteLbaHqVmKoRVp79k8ZSJZ0Xljg83xEc4A0r6_JbHr47KIm0EdoB__DTcnJXOQ",
"profile": "customer"
}
