### ISSUE TITLE
Criar Lambda pra Valida Token

### ISSUE THREAD

**Issue by jcmdsbr** [fiap-8soat-tc-one/tc-backend#46]
Através do beare token no cabeçalho validar se o token é valido para rota em questão (public/private)

**Comment by jcmdsbr** [comment]
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html

**Comment by cisikawa** [comment]
Sobre o fluxo de anônimo, se a rota for publica e não tiver token, a lambda deixa passer e jogamos a responsabilidade para o backend, afinal ele precisaria pegar o customer id do token para buscar esse dado e saber qual valor

**Comment by cisikawa** [comment]
Jean Carlos: curl --location 'http://localhost:8080/api/public/v1/oauth/token' \
--header 'accept: application/json' \
--header 'Content-Type: application/json' \
--data '{ "document": 88404071039}'

Retorna:

{
    "access_token": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI4ODQwNDA3MTAzOSIsImlkIjoiM2ZhODVmNjQtNTcxNy00NTYyLWIzZmMtMmM5NjNmNjZhZmE2IiwibmFtZSI6Ik15bGxlciBTYWthZ3VjaGkiLCJlbWFpbCI6Im15bGxlcnNha2FndWNoaUBnbWFpbC5jb20iLCJkb2N1bWVudCI6Ijg4NDA0MDcxMDM5IiwiaWF0IjoxNzMwODMyMjExLCJleHAiOjE3MzA4MzU4MTF9.-3fSGtEZkm9BzJBv4BRHvPzkteLbaHqVmKoRVp79k8ZSJZ0Xljg83xEc4A0r6_JbHr47KIm0EdoB__DTcnJXOQ",
    "profile": "customer"
}

**Comment by cisikawa** [comment]
curl --location 'http://localhost:8080/api/public/v1/oauth/token/validate' \
--header 'accept: application/json' \
--header 'Content-Type: application/json' \
--data '{ "access_token": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI4ODQwNDA3MTAzOSIsImlkIjoiM2ZhODVmNjQtNTcxNy00NTYyLWIzZmMtMmM5NjNmNjZhZmE2IiwibmFtZSI6Ik15bGxlciBTYWthZ3VjaGkiLCJlbWFpbCI6Im15bGxlcnNha2FndWNoaUBnbWFpbC5jb20iLCJkb2N1bWVudCI6Ijg4NDA0MDcxMDM5IiwiaWF0IjoxNzMwODIwNDU0LCJleHAiOjE3MzA4MjQwNTR9.wsdl4pww6RKfGtQ9BwI209AAyQrrUNtLkYvelQeRPeIShI_0BY-LVffQU_bo4a-YjUNqKQlnrL9aHKljRmG90Q"}'
